# Generated by Django 2.1 on 2019-02-09 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Контрагент')),
                ('description', models.TextField(blank=True, verbose_name='Орисание')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Группа контрагентов')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Группа контрагента',
                'verbose_name_plural': 'Группы контрагентов',
            },
        ),
        migrations.CreateModel(
            name='OrderIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер накладной')),
                ('date', models.DateField(verbose_name='Дата накладной')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Приходная накладная',
                'verbose_name_plural': 'Приходные накладные',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('amount', models.PositiveIntegerField(verbose_name='Колличество')),
                ('discount', models.PositiveIntegerField(verbose_name='Скидка')),
                ('discount_type', models.CharField(choices=[('amount', 'Грн.'), ('percent', '%')], default='percent', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sku', models.CharField(blank=True, max_length=255, verbose_name='Артикул')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Группа товара',
                'verbose_name_plural': 'Группы товаров',
            },
        ),
        migrations.CreateModel(
            name='OrderOut',
            fields=[
                ('orderin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.OrderIn')),
            ],
            options={
                'verbose_name': 'Расходная накладная',
                'verbose_name_plural': 'Расходные накладные',
            },
            bases=('stock.orderin',),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ManyToManyField(to='stock.ProductGroup', verbose_name='Гуппы товара'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(to='stock.Product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='orderin',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Customer'),
        ),
        migrations.AddField(
            model_name='orderin',
            name='order_item',
            field=models.ManyToManyField(to='stock.OrderItem', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='orderin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_groups',
            field=models.ManyToManyField(to='stock.CustomerGroup', verbose_name='Группы контрагентов'),
        ),
    ]
