# Generated by Django 2.1 on 2019-02-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товарная позиция', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='orderin',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Накладная полностью оплачена?'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_type',
            field=models.CharField(choices=[('amount', 'Грн.'), ('percent', '%')], default='percent', max_length=10, verbose_name='Тип скидки?'),
        ),
    ]
