# Generated by Django 2.1 on 2019-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_orderproxy_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(default='шт.', max_length=15, verbose_name='Единица измерения', blank=True),
        ),
    ]
