version: '3.1'

#volumes:
#  pgdata:
#    driver: local
services:
  redis:
    image: redis:latest
    restart: always
  postgres:
    image: postgres:latest
    restart: always
    ports:
    - 5432:5432
    environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
#    volumes:
#    - pgdata:/var/lib/postgresql/data
  celery:
    image: ${IMAGE}
    command: celery -A project worker -l info
    restart: always
    volumes:
    - .:${PROJECT_ROOT}
    depends_on:
    - postgres
    - redis
  celerybeat:
    image: ${IMAGE}
    command: celery -A project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    volumes:
    - .:${PROJECT_ROOT}
    depends_on:
    - postgres
    - redis
  memcached:
    image: memcached:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"