version: '3'

services:
  web:
    container_name: web
    restart: always
    image: xelaxela13/stock:latest
    volumes:
    - .:/srv/www/stock
    expose:
    - 8000
    ports:
    - 8100:8100
    - 8101:8101
    command: python manage.py runserver 0:8100
    depends_on:
    - postgres
    - redis
    - memcached