version: '3.1'

services:
  web:
    restart: always
    image: ${IMAGE}
    volumes:
    - .:${PROJECT_ROOT}
    ports:
    - 8001:8001
    command: "daphne project.asgi:application -b 0.0.0.0 -p 8001"
#    command: "gunicorn -c gunicorn_conf.py project.wsgi"
    depends_on:
    - redis
    - memcached