version: '3'

volumes:
  pgdata:
    driver: local
services:
  redis:
    image: redis:latest
    container_name: redis-stock
    restart: always
  postgres:
    container_name: db
    image: postgres:9.3.22
    ports:
    - 5432:5432
    environment:
    - PGDATA=/var/lib/postgresql/data
    - PORT=5432
    - HOST=db
    - NAME=postgres
    - USER=postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-stock
    environment:
      - SECRET_KEY=D!LS]SC+A\7s3*^YgbNEzsE!^Idnks/u-WM/CTDF(5pi~cI{X
    command: celery -A project worker -l info --pidfile=/run/celery.pid
    restart: always
    volumes:
    - .:/srv/www/stock
    depends_on:
    - postgres
    - redis
  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celerybeat-stock
    environment:
      - SECRET_KEY=D!LS]SC+A\7s3*^YgbNEzsE!^Idnks/u-WM/CTDF(5pi~cI{X
    command: celery -A project beat -l info --schedule=/run/celerybeat-schedule --pidfile=/run/celerybeat.pid
    restart: always
    volumes:
    - .:/srv/www/stock
    depends_on:
    - postgres
    - redis
  memcached:
    image: memcached:latest
    container_name: memcached-stock
    restart: always
    environment:
    - MEMCACHED_HOST=memcached
    - MEMCACHED_PORT=11211
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"