version: '3'

volumes:
  pgdata:
    driver: local
services:
  redis:
    image: redis:latest
    container_name: redis-stock
    restart: always
  postgres:
    container_name: db
    image: postgres:9.3.22
    ports:
    - 5432:5432
    environment:
    - PGDATA=/var/lib/postgresql/data
    volumes:
    - pgdata:/var/lib/postgresql/data
  celery:
    image: xelaxela13/stock:latest
    container_name: celery-stock
    command: celery -A project worker -l info --pidfile=/run/celery.pid
    restart: always
    volumes:
    - .:/home/stock
    depends_on:
    - postgres
    - redis
  celerybeat:
    image: xelaxela13/stock:latest
    container_name: celerybeat-stock
    command: celery -A project beat -l info --schedule=/run/celerybeat-schedule --pidfile=/run/celerybeat.pid
    restart: always
    volumes:
    - .:/home/stock
    depends_on:
    - postgres
    - redis
  memcached:
    image: memcached:latest
    container_name: memcached-stock
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"