version: '3.1'

services:
  web:
    restart: always
    image: ${IMAGE}
    volumes:
    - .:${PROJECT_ROOT}
    ports:
    - 8001:8002
    - 8444:8002
    command: "gunicorn -c gunicorn_conf.py project.wsgi"
    depends_on:
    - postgres
    - redis
    - memcached