version: '3'

services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/srv/www/stock
    ports:
    - 8001:8002
    - 8444:8002
    command: "gunicorn -c gunicorn.py project.wsgi"
    depends_on:
    - postgres
    - redis
    - memcached