version: '3'

services:
  web:
    container_name: web
    restart: always
    image: xelaxela13/stock:latest
    volumes:
    - .:/home/stock
    ports:
#    - 8001:8002
    - 8444:8002
    command: "gunicorn -c gunicorn.py project.wsgi"
    depends_on:
    - postgres
    - redis
    - memcached