version: '3.1'

services:
  redis:
    image: redis:latest
    restart: always
  celery:
    image: ${IMAGE}
    command: celery -A project worker -l info
    restart: always
    user: ${SYSTEM_USER}
    volumes:
      - .:${PROJECT_ROOT}
    depends_on:
      - redis
  celerybeat:
    image: ${IMAGE}
    command: celery -A project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile=
    restart: always
    user: ${SYSTEM_USER}
    volumes:
      - .:${PROJECT_ROOT}
    depends_on:
      - redis
  memcached:
    image: memcached:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"