version: '3'

services:
  web:
    container_name: web
    restart: always
    # указываем откуда собирать образ
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    # монтируем директорию проекта
    volumes:
    - .:/srv/www/stock
    ports:
    - 8001:8002
    # запускаем gunicorn
    command: "gunicorn -c gunicorn.py project.wsgi"
    depends_on:
    - postgres
    - redis
    - memcached