version: '3.1'

services:
  web:
    restart: always
    image: ${IMAGE}
    volumes:
    - .:${PROJECT_ROOT}
    ports:
    - ${UWSGI_PORT}:${UWSGI_PORT}
    command: daphne project.asgi:application -b 0.0.0.0 -p ${UWSGI_PORT}
    depends_on:
    - redis
    - memcached