# Generated by Django 3.2.4 on 2021-06-23 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiplefileupload.models
import sorl.thumbnail.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', sorl.thumbnail.fields.ImageField(upload_to=multiplefileupload.models.upload_file)),
                ('slug', models.SlugField(blank=True, max_length=20)),
                ('show', models.BooleanField(default=True)),
                ('watermarked', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', sorl.thumbnail.fields.ImageField(upload_to=multiplefileupload.models.upload_watermark)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('images', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='multiplefileupload.Image')),
                ('watermark', models.ForeignKey(blank=True, help_text='Optional field. Select a watermark to overlay on images.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='multiplefileupload.watermark')),
            ],
        ),
    ]
