# Generated by Django 2.2.9 on 2020-02-21 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiplefileupload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=multiplefileupload.models.upload_file_to)),
                ('slug', models.SlugField(blank=True, max_length=20)),
                ('thumbnail', models.ImageField(blank=True, help_text='Default thumbnail size 250x250 px, you can change it, rewrite THUMBNAIL_SIZE on settings, THUMBNAIL_SIZE should be a tuple.', upload_to=multiplefileupload.models.upload_thumbnail_to)),
                ('deleted', models.BooleanField(default=False, help_text='Mark as deleted')),
                ('show', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplefileupload.ImagesGallery')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
